### ISSUE TITLE
I can't use the software normally

### ISSUE THREAD

**Issue by 128ev98O** [crskycode/GARbro#56]
When I try to extract the game named "GINKA",it says "File could not be opened as resource archive".And it does the same when I try to open the game included in the original list.
The opened helper menu shows nothing resource archive.
👇This is the picture of the modded edition.👇
![image](https://github.com/user-attachments/assets/a4019121-a523-4091-a199-73b589e9224b)

And the original edition can do so,but it can't extract mostly latest games(Included the "GINKA").
Also can't it do when I copy the newest database as following your steps.
👇This is the picture of the original edition.👇
![image](https://github.com/user-attachments/assets/5f6bc3eb-2cf1-4fa5-aeb5-fc66e4252e4d)

**Comment by liubili** [comment]
我也遇到了同样的问题 不过我解决了
只需要在vs中拉取整个git仓库后自动升级到4.8再自己编译一遍即可

**Comment by quest64** [comment]
From what I understand, the problem is that release files will be marked as blocked on your computer, which means you must unblock them all. To do so, "shift"+"right click" in the Garbro directory and click on "Open Powershell window Here", then run this command in the window:

dir -Recurse | Unblock-File

It should then work normally.
